### ISSUE TITLE
Sort state keys alphabetically

### ISSUE THREAD

**Issue by kiranvarsani** [zalmoxisus/redux-devtools-extension#557] opened 2018-09-27 05:13 UTC
Need ability to sort state keys alphabetically. It is really inconvenient and frustrating to scan through large number of keys.

**Comment by Skywalker13** [comment] 2018-10-26 09:29
duplicate of #416

**Comment by zalmoxisus** [comment] 2018-11-16 18:45
Let's continue this discussion in the original issue.

**Closed by zalmoxisus** 2018-11-16 18:45 UTC
