### ISSUE TITLE
redux-devtools-extension crash whith redux 4.0.0

### ISSUE THREAD

**Issue by Kirpich634** [zalmoxisus/redux-devtools-extension#592] opened 2018-11-28 09:21 UTC
Rredux-devtools-extension v2.16.0 crash whith redux 4.0.0

<img width="1429" alt="screen shot 2018-11-28 at 12 13 11" src="https://user-images.githubusercontent.com/19504525/49141611-0ab93d00-f308-11e8-96e8-c673ff91d89a.png">

**Comment by glennflanagan** [comment] 2018-11-28 09:38
Duplicate of #590

**Comment by jonbjk** [comment] 2018-11-28 09:39
I see same problem

**Comment by saadbinsaeed** [comment] 2018-11-28 09:59
Revert back to the previous version v2.15.5 

- Download [redux-devtool-extension](https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.15.5/extension.zip)
- Extract the zip
- Type `chrome://extensions` into the url
- toggle on developer mode on the top right of the page.
- Click on the **Load Unpacked** button. After clicking the button, Select the extracted folder.

Hope it will help :)

**Comment by akostiv** [comment] 2018-11-28 10:31
@zalmoxisus it helped. App is not crashing at startup anymore

**Comment by Kirpich634** [comment] 2018-11-28 10:37
@zalmoxisus me too, thanks)

**Closed** 2018-11-28 10:39 UTC
