### ISSUE TITLE
White popup. Add example?

### ISSUE THREAD

**Issue by peteruithoven** [zalmoxisus/redux-devtools-extension#4] opened 2015-10-28 09:27 UTC
I've followed the instructions from the readme, but when I visit my project and open the extension it shows a white popup. Probably a javascript error. But I've never made a Chrome extension and I don't know how to debug it. 
It would be great if there was a live example (todo?) website that I could visit to check if it was something in my project (not using `window.devToolsExtension` correctly).

**Comment by peteruithoven** [comment] 2015-10-28 09:48
Following the instructions from https://github.com/zalmoxisus/redux-devtools-extension/issues/2#issuecomment-151603334 I build the dev folder and loaded that as extension and suddenly the location of the exention icon changes and it does show the debugger. 
Extension from: `build/extension`:
![screen shot 2015-10-28 at 10 44 52](https://cloud.githubusercontent.com/assets/523210/10784963/3a143c8c-7d61-11e5-8d56-1941a74ab529.png)
Extension from `dev`:
![screen shot 2015-10-28 at 10 45 27](https://cloud.githubusercontent.com/assets/523210/10784985/555ba5fc-7d61-11e5-9f17-cf536d40045c.png)

This is while trying this on the same project.

**Comment by zalmoxisus** [comment] 2015-10-28 09:58
Yes, in `./build/extension` we have the previous released version, when you do `npm start` you get the upcoming release, which will be released today ;)
I will add the `./buld` to the .gitignore to avoid the confusions.
The main differences are described in #1.
So, the upcoming release works well?

**Comment by peteruithoven** [comment] 2015-10-28 10:12
Ah, thanks that clarifies that, sounds like a great improvement.

But the new (dev) version doesn't fully work I'm getting the following error in my console:
```
Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
  onChange @ page.bundle.js:30356
  (anonymous function) @ createStore.js:52
  dispatch @ createStore.js:50
  dispatch @ page.bundle.js:12277
  (anonymous function) @ bindActionCreators.js:12
  mouseMove @ group.js:374
  handleEvent @ group.js:104
```
The debugger only shows the `@@init` action. 
Using Redux version `3.0.4`. Are there other versions relevant?

**Comment by zalmoxisus** [comment] 2015-10-28 10:20
We have the same issue in #5, but I cannot reproduce it. I just released 0.1.0. Could you please sync the git and try again with `./build/extension`?

**Comment by zalmoxisus** [comment] 2015-10-28 10:22
To check you may just use counter or mvc examples from `./examples`, just do `npm i` and `npm start there`. It should run on port 4001 and 4002.

**Comment by peteruithoven** [comment] 2015-10-28 10:24
I'll check with that example. I'll report issues relating to that `postMessage` in #5. 
If you think it's a good idea this issue could serve as a todo to make a example website.

**Comment by zalmoxisus** [comment] 2015-10-28 10:26
Good suggestion, especially when we'll have the extension on Chrome WebStore.

**Closed** 2015-10-29 08:54 UTC
Labels: enhancement
