### ISSUE TITLE
Immutable.js state and diffs suddenly rendering horribly after 2.15.3 or 2.15.4

### ISSUE THREAD

**Issue by vdh** [zalmoxisus/redux-devtools-extension#581] opened 2018-11-20 08:02 UTC
I think this was caused by one of the recent releases, because this has only started happening today

The diffs are now completely unreadable:
![screenshot 2018-11-20 17 36 54](https://user-images.githubusercontent.com/573501/48758341-75a4bb80-eceb-11e8-9a34-ec35652ac638.png)

The chart tab just dies with "error":
![image](https://user-images.githubusercontent.com/573501/48758460-d46a3500-eceb-11e8-91c5-0436fb1a4a0e.png)

And that "Array of tuples" change from [here in remotedev-serialize](https://github.com/zalmoxisus/remotedev-serialize/pull/9) made it a nightmare trying to navigate through just a normal `Map` & `List` Immutable state. It's even worse than the similar `Array`-crazy pain that the React Dev tools inflicts upon us.

I mean look at this, it's a huge headache:
![screenshot 2018-11-20 17 50 17](https://user-images.githubusercontent.com/573501/48758733-c7017a80-ecec-11e8-9ce8-5ea0326f5b25.png)
The distinction between `List` and `Map` data has been blurred horribly to the point that I can barely tell where I am in the tree anymore.

Compare with this extremely readable layout from [`immutable-object-formatter-extension`](https://github.com/mattzeunert/immutable-object-formatter-extension) (powered by [`immutable-devtools`](https://github.com/andrewdavey/immutable-devtools))
![image](https://user-images.githubusercontent.com/573501/48758900-4131ff00-eced-11e8-968a-64a113177427.png)

**Comment by zalmoxisus** [comment] 2018-11-20 15:59
Thanks for the detailed report! I'm not using ImmutableJS myself and don't remember how the diffs were before. Could it be because of the same PR changing the way of showing Maps/Lists? Do you suggest to just revert that PR or have some ideas of how that could be improved? Would you like to work on a PR there to make it more readable?

**Comment by zalmoxisus** [comment] 2018-11-20 16:00
Except from that PR, serialization was fixed in https://github.com/kolodny/jsan/commit/83d9647541c3643398e3f78de7159675f23861b6 to not lose the reviver, I'm not sure that could be the issue.

**Comment by zalmoxisus** [comment] 2018-11-20 18:39
Disregard the above. I looked into it. The problem is that PR fixes reconstructing the data, but breaks how it is displayed. We could implement ImmutableJS on extension part, but that would require every monitor to support it, so we are just showing what is sent. Transforming Immutable Map into an Object makes it easier for visualization (and diffs), but has the issue with non-string keys, which cannot be used for objects. A solution would be to transform it into ES6 Map as we [added support for it](https://github.com/alexkuz/react-json-tree/pull/69). I tried it now, but there's an issue with `jsan` calling the reviver before data is reconstructed, so we're not getting the Map back. I'll look if that can be addressed, or will just revert that PR for now.

**Comment by zalmoxisus** [comment] 2018-11-20 19:50
That would be a regression anyway as Chart monitor doesn't support ES6 Map. That should be implemented in [`map2tree`](https://github.com/romseguy/map2tree).

For now I reverted https://github.com/zalmoxisus/remotedev-serialize/pull/9 and published `2.15.5` on Chrome Store.

**Closed** 2018-11-20 20:05 UTC
