### ISSUE TITLE
Uncaught TypeError: Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by glenjamin** [zalmoxisus/redux-devtools-extension#112] opened 2016-05-11 17:34 UTC
This happened when toggling actions and on and off.

The full stack trace.
```
VM3847:418
Uncaught TypeError: Cannot read property 'action' of undefined
i @ VM3847:418
(anonymous function) @ VM3847:465
dispatch @ createStore.js:179
r @ VM3847:44
```

It's hard to tell exactly what happened here because of the minification, this is the relevant section of the minified code:

```js
      var s = u[f],
          p = i[s].action,
          l = c[f - 1],
          d = l ? l.state : r,
          v = l ? l.error : void 0,
          y = a.indexOf(s) > -1,
          h = y ? l : o(n, p, d, v);c.push(h);
```

What's the best way to debug this further?

**Comment by glenjamin** [comment] 2016-05-11 17:41
After a bunch of poking around I've established that the error is from this function: https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L106-142

**Comment by zalmoxisus** [comment] 2016-05-11 18:00
@glenjamin, thanks for the report. It seems related to #109.

Unfortunately, the stack trace doesn't help, we still don't know why `actionsById` is empty [here](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L130).

Does the action toggling work even with the exception? Does this happen all the time (if you refresh the page)?

**Comment by glenjamin** [comment] 2016-05-11 18:07
Everything seems to still function correctly, the first time it was happening a lot (multiple errors per click) - after a refresh it was only one at a time.

Might be something to do with whether I'd hit reset?

**Comment by zalmoxisus** [comment] 2016-05-11 18:26
There's something wrong for sure in the injected script as it shouldn't be [dispatched](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L81) several times. So, somehow the [event listener](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L125) was applied multiple times, and `liftedStore` object is not we want to be (probably is not changed from the initial state).

Need to investigate more. Any other details would be welcome.

**Comment by zalmoxisus** [comment] 2016-05-11 18:32
@glenjamin, could you try to add

```js
window.removeEventListener('message', onMessage);
```

before [L125](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L125) to see if it's the case.

**Comment by zalmoxisus** [comment] 2016-05-12 08:54
Well, I managed to reproduce that.

For some reason the store in your app is re-created multiple times, and as the result `window.devToolsExtension` is called several times. So, the event listener is applied [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L125) multiple times and the listener get old values.

I solved that by replacing `window.addEventListener('message', onMessage, false);` in [L125](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L125) with:
```js
if (window.devToolsExtension.__listener) {
      window.removeEventListener('message', window.devToolsExtension.__listener);
    }
    window.addEventListener('message', onMessage, false);
    window.devToolsExtension.__listener = onMessage;
```

Will investigate a bit before publishing, maybe there's a better solution.

Could you check if that solves the issue?

**Comment by glenjamin** [comment] 2016-05-12 09:08
Aha, I understand the issue now.

This is how my store is set up:

```js
let store = redux.createStore(
  reducer,
  redux.compose(
    redux.applyMiddleware(reduxPromise, reduxThunk),
    // If the dev tools extension is installed in the browser
    // then activate it.
    window.devToolsExtension ? window.devToolsExtension() : (f) => f
  )
);

if (module.hot) {
  module.hot.accept();
  module.hot.dispose((data) => {
    data.store = store;
  });
  if (typeof module.hot.data === "object") {
    if (module.hot.data.store) {
      store = module.hot.data.store;
      store.replaceReducer(reducer);
    }
  }
}
```

To keep the logic flatter, the store is rebuilt every time, but if a store already exists in the hot loaded data the new one never gets used.

I think this means your fix won't help me, because it's the old store which actually does the work - I'll update my logic to not create loads of unused stores.

**Comment by zalmoxisus** [comment] 2016-05-12 09:16
I think the solution I provided above should help, because it removes the old listener and listen for the new store applied.

**Comment by glenjamin** [comment] 2016-05-12 09:38
But I actually throw away the new store, and keep using the old one.

I've changed my code to only create a store if one wasn't found in the hot reload data now.

**Comment by zalmoxisus** [comment] 2016-05-12 19:26
@glenjamin, strange I've just checked your snippet, and don't see any problems with it. Anyway, I've just published `1.2.1`, where the listener will not be applied anymore. Let me know if you still experience any troubles.

**Comment by zalmoxisus** [comment] 2016-05-15 17:54
Closing as it wouldn't throw anymore and doesn't seems to be something more to implement here. If you have any ideas what we can do to support such cases better, please let me know.

**Closed by zalmoxisus** 2016-05-15 17:54 UTC
Labels: bug

**Comment by PaulleDemon** [comment] 2023-03-14 16:01
@zalmoxisus I am still experiencing this error. Can you look into what's going on?

I am not sure if this would be of any help, but the error occurs somewhere here 
```
   this.setState({
                        stackFrames: [],
                        showDocsLink: !!r.action && !!r.action.type && "@@INIT" !== r.action.type
                    })
```

**Comment by itorras13** [comment] 2023-07-25 15:33
This is also happening to me suddenly and is throwing in the same spot as @PaulleDemon

**Comment by PaulleDemon** [comment] 2023-07-26 04:58
I had to remove the extension and reinstall it to make it work. I was working on two different projects on the same port, maybe that's why?
