### ISSUE TITLE
Cannot open to right, left or bottom 

### ISSUE THREAD

**Issue by nwehrle** [zalmoxisus/redux-devtools-extension#154] opened 2016-06-30 11:36 UTC
**Expected:** I can open the redux extension to the right (left, bottom) every time I want to.

**Actual:** Just after reinstallation I am able to open to the right (left, bottom) and everything works as expected. After a short amount of time (In the meantime I closed the browser or even shutdown the machine) it does not open in a separate window anymore. Left-click on the toolbar works.

**System:** OSX10.11.5 Chrome 51 and earlier
**Extensions installed:** Redux, React, 1Password, Pocket
**Reproduceable:** Yes, almost every day, 3 different machines with 3 different developers
**Logs:** Do not know how to get them
**Workaround:** Delete and reinstall from store

**Comment by zalmoxisus** [comment] 2016-06-30 13:20
Thanks for the report! 

Logs would help. Could you please copy the error you get from the background page's script?
To do that:

1. Open `chrome://extensions/`
2. Right on the top right side there is a checkbox "Developer mode" you should check.
3.  Find the extension (`Redux DevTools`) and click on "background page" link.

Then instead of deleting and reinstalling the extension you can just click "Reload".

**Comment by zalmoxisus** [comment] 2016-07-01 08:10
@nwehrle, I was able to reproduce it. The reason why I didn't experience it is because I use shortcuts instead of context menu. As a temporal workaround you can also [use shortcuts](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#keyboard-shortcuts) to open the monitors

**Comment by zalmoxisus** [comment] 2016-07-01 09:07
Fixed in `2.2.1`. Please update the extension and let me know if yo experience such problems again.

**Closed** 2016-07-01 09:06 UTC
Labels: bug

**Comment by nwehrle** [comment] 2016-07-01 09:22
Thank you. I'll let you know.

**Comment by nwehrle** [comment] 2016-07-04 12:17
Works flawlessly!
