### ISSUE TITLE
No vertical scrolling for State view - Tree tab

### ISSUE THREAD

**Issue by jpdelatorre** [zalmoxisus/redux-devtools-extension#266] opened 2016-11-28 20:15 UTC
The version 2.11.0 in Chrome v54.0.2840.98 (64-bit) Mac, doesn't allow you to scroll vertically

**Comment by jasongonzales23** [comment] 2016-11-28 21:12
+1 

The right hand panel of the screenshot below is not scrollable. Just need to set overflow: scroll on the appropriate container. Should be a fast fix. I'd be happy to jump in and contribute later today if it would help.

![image](https://cloud.githubusercontent.com/assets/243861/20686127/38dd422a-b56c-11e6-9da1-64452b29ba3e.png)

**Comment by zalmoxisus** [comment] 2016-11-29 09:48
Should be fixed in `2.11.0.4` (https://github.com/zalmoxisus/remotedev-monitor-components/pull/1), which was published on Saturday. Please check if you have the latest version. I cannot reproduce the issue on Mac.

**Comment by jasongonzales23** [comment] 2016-11-29 15:58
To get the update I uninstalled the extension and reinstalled it, then the issue was fixed. Is there another mechanism for forcing an update?

**Comment by zalmoxisus** [comment] 2016-11-29 16:24
@jasongonzales23 Chrome autoupdates the extension automatically, but the extension could be in use (due to some pages using it), so restarting the Chrome should help in this case. Another option is to enable developer mode on `chrome://extensions`, then there will be a new button `Update extensions now`.

Will try to bring an option to update the extension explecitely. Thanks for the reports!

**Closed by zalmoxisus** 2016-11-29 16:24 UTC

**Comment by jasongonzales23** [comment] 2016-11-29 16:54
I "rebooted" chrome and it didn't update (I use the beta channel, so that *may* have something to do with it?), but thanks for the reminder about developer mode!
