### ISSUE TITLE
Firefox: bottom of tool scrolls out of view

### ISSUE THREAD

**Issue by FLamparski** [zalmoxisus/redux-devtools-extension#377] opened 2017-06-24 08:57 UTC
See:
![image](https://user-images.githubusercontent.com/912935/27507261-5fb2cf50-58c3-11e7-8a14-0005dbf6e046.png)

I'm using Firefox 54.0.

**Comment by MichalWadowski** [comment] 2017-07-07 08:08
I have similar problem on every Redux Dev Tools window. When I click redux icon in address bar, open bottom/left/right window or in developers tools, the content of ReduxDevTools doesn't fit to window within it's open. I have to manually scroll window content by pressing UP/DOWN on keyboard.

But if content is small, and scrolls doen't show up, then everything looks fine.

![screen_1](https://user-images.githubusercontent.com/7845843/27948986-26fd3374-62fc-11e7-8443-c4594e4e4655.png)
![screen_2](https://user-images.githubusercontent.com/7845843/27948985-26fb1436-62fc-11e7-8e78-1d5b0a8d70f0.png)
![screen_3](https://user-images.githubusercontent.com/7845843/27948983-26d512c2-62fc-11e7-8a57-701b796270b9.png)

**Comment by GuillaumeAmat** [comment] 2017-07-18 09:00
Oh, I just noticed that you can see the bottom part of the tool by pressing the down arrow key.

1. Open the devtools
2. Go to the Redux tab
3. If the content is too tall (eg. on the state screen), the bottom of the content is hidden (like an "overflow: hidden")
4. Press the down arrow of your keyboard
5. The content "scrolls" to the bottom
6. Press the up arrow and you go back to the top

**Comment by MichalWadowski** [comment] 2017-07-19 06:46
Yes, I can see bottom part of devtools by pressing arrows on keyboard. But it is uncomfortable to scrolling up/down all the time (I can't scroll by mouse).

ReduxDevTools on google chrome doesn't have this issue, it's fit how it should be.

**Comment by GuillaumeAmat** [comment] 2017-07-19 07:06
Agreed @MichalWadowski, it's not comfortable. But in the meantime, we can use it ;)

**Comment by MazeChaZer** [comment] 2017-09-11 08:40
In Firfox Nightly 57, I cannot use the arrow key workaround anymore. This is very annoying.

**Comment by MazeChaZer** [comment] 2017-09-17 16:24
This line looks very suspicious: https://github.com/zalmoxisus/redux-devtools-extension/blob/a244e254c28506e478d579f58ea0b50de4bc2517/src/browser/views/devpanel.pug#L10
@zalmoxisus Can you reproduce this issue? This seems to be very annoying for some users and looks like it's easy to fix.

**Comment by MazeChaZer** [comment] 2017-09-19 09:19
Nevermind about my previous hint, that was bogus.

**Comment by MazeChaZer** [comment] 2017-09-19 09:54
I believe I found where the problem comes from.
The body of the Redux devtools has `position: fixed` and `height: 100%`:

https://github.com/zalmoxisus/remotedev-app/blob/19c8a3607ea85c0da23a68eb75677272f8d59edc/src/views/index.pug#L9
https://github.com/zalmoxisus/remotedev-app/blob/19c8a3607ea85c0da23a68eb75677272f8d59edc/src/views/index.pug#L11

Because of this combination, 100% means the total height of the develop tools, including the tab bar. This makes the height of the Redux view too tall, exactly by the height of the tab bar.
Removing the `position: fixed` from the `body` element might solve the problem. Perhaps a CSS like this could do the job: http://jsbin.com/rohaquropu/edit?html,css,output
That example expects `width: 100%` on `html` and `body`, so this might not work.

I would really like to tinker with this myself instead of doing guesswork, but I currently don't have the time to setup an Add-On development environment for myself.

**Comment by zalmoxisus** [comment] 2017-09-19 16:25
That position fixed is necessary for the popup from location bar. We could use different styles for the devpanel. However, I was working on [a new UI](https://github.com/zalmoxisus/remotedev-app/pull/30), which should solve this issue as well. Unfortunately, didn't have much time for oss recently.

**Comment by Gaya** [comment] 2017-11-22 09:32
Love using Firefox and the extension, so solving this issue would make it even better.

@zalmoxisus how far along with the new UI are you? If you're not really there yet I would like to invest some time and take a look at this issue and do a fix for the time being.

**Comment by Gaya** [comment] 2017-11-22 10:16
Found out `.inspector-0-0` needs an `overflow: auto` to fix some of the content disappearing. This happens because in Firefox, this remote dev inspector container keeps growing.

The styling of which I was able to trace back to https://github.com/zalmoxisus/remotedev-inspector-monitor/blob/remotedev-inspector/src/utils/createStylingFromTheme.js#L41

Submitted a pull request which will solve this problem.

https://github.com/zalmoxisus/remotedev-inspector-monitor/pull/2

**Comment by meiriko** [comment] 2017-11-22 14:08
had a similar problem, commented on a closed ticket, here is the text again:

I have a similar issue:

![image](https://user-images.githubusercontent.com/1743547/33131289-c340da1a-cf9e-11e7-8c29-4f1c42c9f77d.png)

I tracked it down to missing height on an element. The element is:

`<div class="actionListRows-4144605864" style="">`

When you assign it:

`flex: 1 1 0;`

it renders okay:

![image](https://user-images.githubusercontent.com/1743547/33131374-076795da-cf9f-11e7-9bad-2caa89cef184.png)

**Comment by rahulthewall** [comment] 2017-12-07 14:31
Any ETA on when a fix lands (as it seems that @eppsilon's commit has fixed the issue)? I would prefer not to switch to Chrome to debug :)

**Comment by Fensterbank** [comment] 2017-12-15 10:13
So we have two pull requests trying to fix this but nothing happens here :(
This bug is really annoying, I don't understand why Firefox get this low priority here...

**Comment by ChenXiyu** [comment] 2017-12-27 02:29
Facing the same issue,on firefox 58, sense we already have solutions, but why this bug takes so long and still exists?

**Comment by gluxon** [comment] 2018-01-22 17:04
I ended up adding the following to [userContent.css](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Modifying_the_Default_Skin#Customize_with_userChrome.css) as a temporary workaround.

```css
.inspector-331775157 {
  min-height: 0;
}
```

**Comment by ibrahima** [comment] 2018-02-13 21:35
Thanks for mentioning the workaround! This seems like a good approach until your fix can be merged.

**Comment by zalmoxisus** [comment] 2018-03-02 15:39
Fixed in version `2.15.2` of the extension. It's available on AMO. Sorry about the delay!

**Closed by zalmoxisus** 2018-03-02 15:39 UTC

**Comment by Gaya** [comment] 2018-03-02 15:42
Awesome, thanks!

**Comment by mpicard** [comment] 2018-03-02 19:12
Woo!
