### ISSUE TITLE
Uncaught TypeError causing unclickable actions

### ISSUE THREAD

**Issue by shark0der** [zalmoxisus/redux-devtools-extension#139] opened 2016-06-14 11:24 UTC
I'm getting "Uncaught TypeError: Cannot read property 'hasOwnProperty' of null" when some actions are fired and every time the action is clicked (therefore preventing the action to be selected). The workaround that I'm using at the moment is that I click the "skip" button twice (skip and then unskip) and afterwards I'm able to select the action.

Here's a screenshot so you can see the context and the stack trace:

![ss](https://cloud.githubusercontent.com/assets/528959/16040646/de4b6ace-3228-11e6-9298-f6ed7534c9bc.png)

Unfortunately I can't debug it myself as the time does not allow it at the moment, but I can provide more information as needed.

**Comment by zalmoxisus** [comment] 2016-06-15 14:09
Thanks for the report! Can you reproduce it with [our demos](https://github.com/zalmoxisus/redux-devtools-extension#demo)? Could you provide some steps to reproduce it because I cannot?

Maybe @alexkuz has any ideas from where it can come?

**Comment by zalmoxisus** [comment] 2016-10-05 11:48
Fixed in https://github.com/alexkuz/redux-devtools-inspector/pull/44.

**Closed by zalmoxisus** 2016-10-05 11:48 UTC
Labels: bug
