### ISSUE TITLE
Redux Devtools Extension doesn't reflect the latest state

### ISSUE THREAD

**Issue by lukebarton** [zalmoxisus/redux-devtools-extension#249] opened 2016-11-04 14:20 UTC
Just updated to 2.9.1.0 from 2.8.5.x (I think) and there appears to be an issue with reflecting the current state. This was not an issue in 2.8.5.x. 

For example, an action updates the state, however, the diff and state panes on Redux Devtools extension do not show the state being updated, despite seeing the result of the state being reflected in the app. Pressing the "Pause" button within Devtools seems to resync the state and shows it correctly. Sometimes this actually changes the diffs from previous actions, as demonstrated in video2.

This *may* (probably) be a Devtools bug, but I haven't integrated it into the app to test.

https://dl.dropboxusercontent.com/u/8812332/redux-devtools-bug.mov
https://dl.dropboxusercontent.com/u/8812332/redux-devtools-bug2.mov

**Comment by zalmoxisus** [comment] 2016-11-04 15:01
@lukebarton, yes, it seems related to the introduced `latency` parameter and the timeouts in `2.9.0`. Could you please provide an example and steps to reproduce so I could figure it out?

Also, try to set `latency` parameter to `0` to see if it helps:
```js
const store = createStore(rootReducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__({
  latency: 0
}));
```

**Comment by kanzelm3** [comment] 2016-11-04 15:43
@zalmoxisus setting the latency to 0 fixes the issue for me. I was seeing the same thing. I feel like 0 should probably be the default value for latency.

**Comment by zalmoxisus** [comment] 2016-11-04 15:51
@kanzelm3, it was. We want to guarantee that the extension is performant out of the box, so it will not freeze highly updated apps like in [the demo](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.9.0). Usually, we cannot percept more than an action in 500 ms (which is by default), so no need to waste the cpu.

However, missing the current state due to timeout is a bug we should address. Just cannot reproduce :-/

**Comment by lukebarton** [comment] 2016-11-04 17:55
Setting `latency` to `0` isn't fixing it for me.

I'm using redux-saga and these actions are dispatched in `fork`d sagas. If I do them sequentially with `call`, Devtools plays fine. But if I async `fork` them Devtools does not. 

Initial
action A
action B -> Async
action C -> Async

When B resolves, it seems to forget the changes caused by action A and thinks that action B reverted whatever action A did, like it cached the state or something. It also doesn't actually reflect the true changes by action B in the diff.

Until I press that pause button :)

**Comment by zalmoxisus** [comment] 2016-11-04 18:16
@lukebarton could you please modify [our example with Redux Saga](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/examples/saga-counter) to replicate that?

**Comment by zalmoxisus** [comment] 2016-11-04 18:43
@lukebarton, I modified the example as following and not getting the issue:
```js
import { takeEvery } from 'redux-saga'
import { take, put, call, fork, select } from 'redux-saga/effects'
import { delay } from 'redux-saga'

export function* incrementAsync() {
  yield call(delay, 0)
  yield put({type: 'INCREMENT'})
}


function* watchDecrement() {
  while(true) {
    yield take('DECREMENT')
    yield fork(incrementAsync)
    yield fork(incrementAsync)
  }
}

export default function* rootSaga() {
  yield [
    fork(watchNavigate)
  ]
}
```

I'm dispatching `DECREMENT` and see `-1` > `0` > `1`. Am I missing anything?

**Comment by valdemars** [comment] 2016-11-05 20:13
I have the same problem, latency:0 isn't fixing
In my case: 
When app load first - store data is empty, but in action payload data is not empty, and in DIFF tab - states are equal (but really store is updated in app, and states are not equal). 
**But**, when I click on pause/start recording button - data appears in a store.
**Video:** 
http://sendvid.com/3f82tyzg
https://www.dropbox.com/s/dhwyhpd67ypcva0/bug.mp4?dl=0

**Comment by zalmoxisus** [comment] 2016-11-05 20:33
@valdemars, thanks for the details. Unfortunately, video doesn't help much. You can help us by providing a repo to replicate the issue. If you cannot share your project, [there are examples](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/examples) you can change in order to reproduce this behaviour.

**Comment by zalmoxisus** [comment] 2016-11-05 20:48
Just to clarify, when you click `Pause` or dispatch any other monitor action, the whole history is sent to the extension, that's why there's no problem in that case. However, in other cases we're a sending to the extension only new changes (for performance reason).

Normally, the state is changed before our `store.subscribe` is invoked so there shouldn't be such behaviour like in those videos, but something goes wrong, and having a repro case it would be easy to fix.

In case you want to figure it out yourself, it's just [this script](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js) to investigate.

**Comment by somghosh** [comment] 2016-11-06 17:40
@zalmoxisus it seems like on my chrome this issue is fixed now. All the correct DIFFs in state are being shown. I am still scratching my head trying to understand what happened (i checked that you didn't release any new version)

**Comment by zalmoxisus** [comment] 2016-11-07 18:54
@somghosh in fact [there were `2.9.1` and `2.9.2` published these days](https://github.com/zalmoxisus/redux-devtools-extension/commits/master), just didn't add a release tag here as they are mostly blind patches :-/

**Comment by maxime1992** [comment] 2016-11-08 10:02
@zalmoxisus I think I do have the same problem and I can help you to reproduce : 

```
git clone https://gitlab.com/victornoel/petals-cockpit.git
cd petals-cockpit/frontend
npm i
./node_modules/angular-cli/bin/ng serve
```

Open your browser at : [http://localhost:4200/cockpit/workspaces](http://localhost:4200/cockpit/workspaces)

Now if we look at the state, we have something like : 
![image](https://cloud.githubusercontent.com/assets/4950209/20094339/15b84c84-a5a1-11e6-9b31-f19eeaa1ec1a.png)

Then click on the + button : 
![image](https://cloud.githubusercontent.com/assets/4950209/20094697/b2ccf424-a5a2-11e6-8bac-b969e224db18.png)

and add for example "test"

The state chart is the same : 
![image](https://cloud.githubusercontent.com/assets/4950209/20094339/15b84c84-a5a1-11e6-9b31-f19eeaa1ec1a.png)

BUT if you click on "log monitor" or "inspector" and then come back on "chart" it's updated to : 
![image](https://cloud.githubusercontent.com/assets/4950209/20094625/71043462-a5a2-11e6-90b4-7ca6e6cf02c3.png)

(notice the 3 minimal workspaces on the right instead of 2)

**Comment by zalmoxisus** [comment] 2016-11-08 10:51
@maxime1992, thanks for the example.

However the current issue is Redux specific, while you're using the extension API directly via nrgx store devtools.

The issue you're having is related to Chart Monitor only, the same error as in https://github.com/romseguy/redux-devtools-chart-monitor/issues/11. I'll look into it.

**Comment by maxime1992** [comment] 2016-11-08 12:00
Woops I misunderstood. Thanks for pointing the other issue and for looking into it.

**Comment by zalmoxisus** [comment] 2016-11-10 14:32
@maxime1992 it should work in `2.10.0`, [here](https://github.com/ngrx/store-devtools/issues/38#issuecomment-259704023) are more details why that was happening. Thanks again  for the example!

**Comment by zalmoxisus** [comment] 2016-11-10 14:34
@lukebarton, @valdemars could you please check if you're still experiencing the issue in `2.10.0`. If yes, please amend [my example](https://github.com/zalmoxisus/redux-devtools-extension/issues/249#issuecomment-258515651) to reproduce that.

**Comment by maxime1992** [comment] 2016-11-10 16:10
@zalmoxisus it's fixed, thanks a lot ! =)

**Comment by agreco** [comment] 2016-11-14 21:22
Hey, just stumbled upon this..

How do I add the latency param via `const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;`. 

Thanks in advance.

**Comment by zalmoxisus** [comment] 2016-11-15 08:54
@agreco,
```js
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
 window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({ latency: 0 }) : compose;
```

If you could provide a repo or an example to reproduce the problem, it would help.

**Comment by agreco** [comment] 2016-11-15 09:04
@zalmoxisus thanks! I was using the first approach and then spotted the `__COMPOSE__` method 👍

**Comment by zalmoxisus** [comment] 2016-11-15 09:38
@agreco did that help? I'm still unable to replicate this issue. Maybe you could provide more details?

**Comment by agreco** [comment] 2016-11-15 09:45
@zalmoxisus Oh sorry, there was no issue :) I can confirm that your suggestion works! 

It was me just reimplementing the `window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()` to use `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`.

This was the first place I stumbled upon before reading the docs.

**Comment by zalmoxisus** [comment] 2016-11-16 10:03
Closing this.

@lukebarton, @valdemars if you're still experiencing this issue with the latest please let me know.

**Comment by arjunu** [comment] 2016-11-16 11:56
@zalmoxisus issue is still there in 2.10.1.1. I'm unable to reproduce it on a smaller project.

Also for some reason the slider is not at the end when i open it. Is that related to this? Nothing happens when I drag it till the end. If I click pause, state is updated.

<img width="570" alt="screen shot 2016-11-16 at 3 56 02 pm" src="https://cloud.githubusercontent.com/assets/4038217/20346409/db30e9f4-ac21-11e6-88d7-bc921d5ff6c0.png">

**Comment by zalmoxisus** [comment] 2016-11-16 13:39
@arjunu, yes it should be related. Are you using any filter parameters?

**Comment by arjunu** [comment] 2016-11-16 15:10
@zalmoxisus  There are no exceptions. What do you mean by filter parameters? Is it the search box in Inspector?

**Comment by zalmoxisus** [comment] 2016-11-16 15:13
@arjunu I mean that you can filter actions whether specifying them on the extension setting page or by using `actionsWhitelist` / `actionsBlacklist` parameters. In other words are you specifying any parameters?

**Comment by arjunu** [comment] 2016-11-16 15:13
@zalmoxisus Nope.

**Comment by zalmoxisus** [comment] 2016-11-16 17:53
@arjunu I'm still stuck in reproducing that. Do you also use redux-saga? Does that happen when starting the app (like in @valdemars' video)? The slider's position isn't accurate everytime the state is altered? Maybe you can find something in [my example](https://github.com/zalmoxisus/redux-devtools-extension/issues/249#issuecomment-258515651) we can change to correspond to the behaviour of your app?

**Comment by arjunu** [comment] 2016-11-16 18:48
@zalmoxisus Yes I use redux-saga. When my app loads a bunch of sync actions and async are dispatched. I use code splitting and async reducer injection. Until my chunk loads (I'm dispatching actions to show/hide loader for loading chunks as they're huge) the state is up to date in the inspector. Post that it's not updated. The diff section either shows "states are equal" or a previous action's diff. 

I continue to use the app and somewhere down the line for an action (synchronous) the state is up to date. Or if I click Pause. This happens every 9 of 10 times.

The slider thing happens every 1 of 5 times. I tried to replicate the issue on a smaller project with the same setup as mine (with sagas, routes and code splitting). No luck. This issue wasn't there in version 2.8.x.

I used the export option to see what it's like before and after the state is correct. But I'm seeing:
```json
{
    "payload": {}, "previousState": {}
}
````

Didn't it used to be seomthing like:
```json
{
    "actionsById": {},
    "computedState": {}
}
```

**Comment by zalmoxisus** [comment] 2016-11-16 19:09
Yes, we've changed the format of the exported file in the latest. Before it included a lot of unnecessary data. Anyway, it wouldn't help to debug as the data to export are requested from the client side again.

To inspect the extension's state:

1. Open `chrome://extensions/`, check `Developer mode` on the top of teh page, find the extension and click `background page` link. 
2. In the console you can call `store.getState().instances.states`. 
3. Don't pay attention to the `default` key of that object, go to the other one with autogenerated key. The object inside should be equivalent to your application's lifted state (generated by redux devtools enhancer).

Signs that something is wrong: `stagedActionIds` length is not the same as `computedStates` length and as `actionsById` keys length.

Also inside you app you could expose the store globally and check if `store.liftedStore.getState()` is the same as that object.

**Comment by arjunu** [comment] 2016-11-16 19:16
@zalmoxisus 
you're correct
<img width="307" alt="screen shot 2016-11-17 at 12 46 27 am" src="https://cloud.githubusercontent.com/assets/4038217/20361910/54c72552-ac5f-11e6-9f94-532f17bda3e4.png">

**Comment by zalmoxisus** [comment] 2016-11-16 19:18
@arjunu did you dispatched 14 actions or 19? To understand whether the actions or sates were sent wrong.

**Comment by arjunu** [comment] 2016-11-16 19:20
@zalmoxisus 14. Once I click pause both arrays become 15 in length.

**Comment by zalmoxisus** [comment] 2016-11-16 19:48
Well, I added a tweak to prevent sending the same state history multiple times, though I still don't know why it is happening.  Published `2.10.1.2` which should appear on Chrome Store in about an hour. Please give it a try.

**Comment by arjunu** [comment] 2016-11-17 05:19
@zalmoxisus Still the same with 2.10.1.2.

**Comment by zalmoxisus** [comment] 2016-11-17 11:33
@arjunu, could you please give a try to `2.10.1.3` I've just published? If that still doesn't help, then we need an example to reproduce.

**Comment by arjunu** [comment] 2016-11-17 11:41
@zalmoxisus Sorry, still the same.

**Comment by zalmoxisus** [comment] 2016-11-18 09:17
@arjunu is the same problem (of having more states than actions) when [`latency` is set to `0`](https://github.com/zalmoxisus/redux-devtools-extension/issues/249#issuecomment-258454885)?

**Comment by tomxtobin** [comment] 2016-11-18 18:36
Is anyone else experiencing this issue using `actionsBlacklist`, by any chance?

I noticed missing actions after switching my async over to redux-saga. While trying to figure out what was going on, I also noticed that my `actionsBlacklist` setting wasn't being respected; quite a few instances of the blacklisted actions were still coming through.

When I removed `actionsBlacklist` entirely, the missing-action issue seemed to be resolved. (Although it's harder to see the actions I care about now that they're swamped by all the actions I previously blacklisted.)

Trying `latency: 0` didn't seem to have any effect on this bug one way or the other.

I'm using `2.10.1.3`, FWIW.

**Comment by zalmoxisus** [comment] 2016-11-19 10:16
@tomxtobin I guess the problem still occur without `actionsBlacklist`, but maybe not that frequently or isn't so obvious that the states don't correspond.

Most likely it is related to some weird behaviour of our subscribe, as [stated in the docs](http://redux.js.org/docs/api/Store.html#subscribe):
> The listener should not expect to see all state changes, as the state might have been updated multiple times during a nested dispatch() before the listener is called.

If I had a repro case, I'd play with it to find a solution.

Maybe someone could try to change [saga async example](https://github.com/yelouafi/redux-saga/tree/master/examples/async) to replicate this problem as it seems most appropriate to the described use case. I didn't have any luck to see any problems with it.

Just change [this file](https://github.com/yelouafi/redux-saga/blob/master/examples/async/src/store/configureStore.js):

```diff
export default function configureStore() {
+  const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
  const sagaMiddleware = createSagaMiddleware({sagaMonitor})
  return {
-    ...createStore(rootReducer, applyMiddleware(sagaMiddleware)),
+    ...createStore(rootReducer, composeEnhancers(applyMiddleware(sagaMiddleware))),
    runSaga: sagaMiddleware.run
  }
}
```

Then try to alter the tasks [here](https://github.com/yelouafi/redux-saga/blob/master/examples/async/src/sagas/index.js).

**Comment by zalmoxisus** [comment] 2016-11-19 19:14
I did a complete rewrite of that part, and have just published `2.10.2`.

@tomxtobin, @arjunu, and others who was experiencing this issue, could you please give it a whirl with and without setting `latency`?

**Comment by arjunu** [comment] 2016-11-20 10:25
@zalmoxisus It's working now!

**Comment by zalmoxisus** [comment] 2016-11-22 14:27
To clarify, before we were batching/sending actions via `setTimeout`, but now via lodash `throttle`, which sends the leading event in the same tick. Not sure we could get the same problem as before with the trailing event.

If someone is still experiencing this issue please let me know.

**Closed by zalmoxisus** 2016-11-22 14:27 UTC
Labels: bug, cannot-reproduce, help wanted

**Comment by tomxtobin** [comment] 2016-11-22 17:53
It's working for me now, too (even with `actionsBlacklist`). Thanks!

**Comment by mustafaekim** [comment] 2017-07-01 09:16
I am having the same issue. 2 consecutive events (raw)

1. EVENT
```ts
{
  payload: {
    connectionStatus: 0
  },
  type: '[EventClient] CONNECTION STATUS UPDATE'
}
```

2. EVENT
```ts
{
  payload: {
    connectionStatus: 1
  },
  type: '[EventClient] CONNECTION STATUS UPDATE'
}
```

The state changes. However the Diff part of ngrx devtools says (states are equal)

**Comment by NLSVTN** [comment] 2021-06-23 16:54
I am using redux dev tools chrome extension - **2.17.2**, and my code is the following one:

```
/* eslint-disable no-underscore-dangle */
const composeEnhancers = (window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ &&
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({ trace: true, traceLimit: 25 })) || compose
/* eslint-enable */
const enhancer = composeEnhancers(
  applyMiddleware(thunkMiddleware, persistStoreMiddleware),
)
```

The state that I see in the extension is different from the one accessed by **getState()** function.

**Comment by saswatsam786** [comment] 2022-07-30 06:10
I have an issue with redux developer tools. My action seems to work fine but state, diff, and others show null or undefined.
How do I fix that? Please help. I tried each and every method written above.
Here are the images:
<img width="512" alt="Screenshot 2022-07-30 at 11 36 48 AM" src="https://user-images.githubusercontent.com/77463804/181877205-4057148a-5119-438b-a752-c570172d1ca9.png">
<img width="520" alt="Screenshot 2022-07-30 at 11 36 40 AM" src="https://user-images.githubusercontent.com/77463804/181877208-20bdea73-d702-4051-be86-86fc76c03630.png">


Here the action tab is good but the state tab isn't showing anything.
Anyone could help.
