### ISSUE TITLE
See callstack for events.

### ISSUE THREAD

**Issue by joshsten** [zalmoxisus/redux-devtools-extension#429] opened 2017-11-16 16:44 UTC
A problem is finding the source of events in the event list. It'd be nice to have an option to click an event and view the callstack that triggered the event.

**Comment by oleggromov** [comment] 2018-01-14 15:29
It would be really useful, especially since debugging in redux sometimes becomes unfairly tricky.

**Comment by markerikson** [comment] 2018-06-23 01:11
This is a great idea!  Don't have time to try adding this myself, but it'd be a fantastic addition.

**Comment by mpeyper** [comment] 2018-06-23 01:12
Came here to create the same issue.

@markerikson [proposed a middleware for doing this](https://twitter.com/acemarke/status/1010259708714868736), but I think it would be incredibly useful as part of the dev tools extension.

**Comment by markerikson** [comment] 2018-06-23 01:13
The DevTools implementation would need to capture the stack trace for later use, not just log it to the console, but yes - this would be a HUGE benefit.

**Comment by mpeyper** [comment] 2018-06-23 01:18
I believe something like [`new Error().stack`](not sure if it's a good idea though](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stac) will give capture the current stack trace... not sure if it's a good idea though:

> Different browsers set this value at different times. For example, Firefox sets it when creating an Error object, while PhantomJS sets it only when throwing the Error, and MSDN docs also seem to match the PhantomJS implementation.

**Comment by theKashey** [comment] 2018-08-04 00:40
Generating stack traces is a pain. Thank's god we have got [stacktrace.js](https://github.com/stacktracejs/stacktrace.js/)!

**Comment by markerikson** [comment] 2018-08-29 04:03
A couple quick thoughts on filtering stack traces.  I'm currently using `stacktrace-js` to parse the serialized `Error` and turn it into an array of stack frame objects (including using sourcemaps to clean up the files and paths).  Searching around, there's a lib called https://github.com/xpl/stacktracey that looks like it can do some of the same things, but also filter the results based on certain libs.  

There's also [the code in the `react-error-overlay` package used by CRA to parse errors](https://github.com/facebook/create-react-app/tree/a671462c1089c1afe95cc1f9d4f2432d3a885806/packages/react-error-overlay/src/utils), too.  That code in particular is really interesting, because it not only cleans up source lines and uses sourcemaps, it actually highlights the line where the error occurred WITH the original source if available, like this:

![cra error overlay](https://user-images.githubusercontent.com/1128784/44764681-e68a6c00-ab1e-11e8-91ba-7b7149b32332.png)

It'd be cool if we used that approach to highlight where the action was dispatched.  I imagine it would take some heuristics, though, because otherwise a lot of it might be just the internals of `bindActionCreators()`.

**Comment by theKashey** [comment] 2018-08-29 07:41
Is it possible to trace "async" events, like button->click->event->saga->event->saga->event....?

**Comment by markerikson** [comment] 2018-08-29 15:21
@theKashey : that one I'm not sure about.  I know that the actual browser debuggers can link together things like that, but I have no idea how that's implemented.

**Comment by markerikson** [comment] 2018-09-01 22:30
Today I was able to use the stack trace parsing logic and display UI from `react-error-overlay`, and cram it into the "Stack" tab in the DevTools Extension.  A couple examples:

A click handler from my "Project Mini-Mek" sample app:
![redux devtools extension - cra overlay - project mini-mek](https://user-images.githubusercontent.com/1128784/44950401-e20ecd80-ae14-11e8-8cc9-1a390e2cebb1.png)

An action from the new Reddit UI:
![redux devtools extension - cra overlay - new reddit](https://user-images.githubusercontent.com/1128784/44950403-ed61f900-ae14-11e8-9aaf-b5fb38229b97.png)

I've pushed the changes to the `remotedev-app` PR linked earlier in the issue.

At this point, there's a couple major issues:

- The PR code is pretty hacked-up and required Babel config changes to build okay
- @zalmoxisus hasn't been very active lately

So, I'm not sure when we might actually manage to get this merged in and an updated version of the DevTools released.

**Comment by mpeyper** [comment] 2018-09-02 00:02
If you want to make a PR, I'm happy to help with code review to help get the code cleaned up. Can't help with maintainer activity.

**Comment by markerikson** [comment] 2018-09-02 00:13
PRs are already open and linked above, but I'll re-link them here:

https://github.com/zalmoxisus/redux-devtools-instrument/pull/21
https://github.com/zalmoxisus/remotedev-app/pull/43

The `remotedev-app` one has almost all the changes, and thus the one that needs cleaning up.

**Comment by markerikson** [comment] 2018-09-02 19:49
Since I'm not sure when this will be merged in, I'm going to attach unofficial builds of the extension for Chrome and Firefox.

**Chrome**


1. Download [Redux DevTools Extension with action stack traces - Chrome.zip](https://github.com/zalmoxisus/redux-devtools-extension/files/2343699/Redux.DevTools.Extension.with.action.stack.traces.-.Chrome.zip)
2. Double-click to extract
3. Visit chrome://extensions
4. Ensure "Developer Mode" is enabled
5. Click "LOAD UNPACKED"
6. Select extension

**Firefox**


1. Download [Redux DevTools Extension with action stack traces - Firefox.zip](https://github.com/zalmoxisus/redux-devtools-extension/files/2343698/Redux.DevTools.Extension.with.action.stack.traces.-.Firefox.zip)
2. Visit about:debugging
3. Click "Load Temporary Add-on"
4. Select extension


It definitely looks like clicking on a stack trace entry will _not_ open the debugger in Firefox, because the `chrome.devtools.panels.openResource()` API is not available in Firefox, and I don't know what its equivalent is (if any).  But, seeing the file name and potentially the lines should be an improvement, and you can always manually open that file yourself.

**Comment by digitarald** [comment] 2018-10-31 16:16
> the chrome.devtools.panels.openResource() API is not available in Firefox

Filed as [bug 1503475](https://bugzilla.mozilla.org/show_bug.cgi?id=1503475).

**Comment by zalmoxisus** [comment] 2018-11-16 18:09
@markerikson did a great job working on this, but, as mentioned, it's still first step and there're some parts to finalize before moving to production, as discussed in zalmoxisus/remotedev-app#43. Also it was implemented against master branch which is old and everything is rewritten in another branch, so I'll have to reimplement it there. I'll finish with critical issues and come back to this one, if someone wants to help, I can assist with more details on what should be done.

Meanwhile can install the package kindly provided by Mark in https://github.com/zalmoxisus/redux-devtools-extension/issues/429#issuecomment-417955282. Or for only seeing callstack (without`react-error-overlay` ui part and jumping to the source), can just add `stack: window && window.__REDUX_DEVTOOLS_EXTENSION__ ? Error().stack : undefined` in the root reducer. That's exactly what we're sending to the extension.

As discussed in zalmoxisus/redux-devtools-instrument#21, for this feature we'll add [`shouldIncludeCallstack`](https://github.com/zalmoxisus/redux-devtools-instrument#api) parameter. If someone can benchmark `const stack = Error().stack` in different scenarios and it doesn't have significant performance impact to consider as a regression, we can enable it by default. I suspect it would depend on many factors.

**Comment by zalmoxisus** [comment] 2018-12-15 22:52
I did some tweaks in reduxjs/redux-devtools#418 and it's almost ready. Have to finish some other work, and should have `2.17` published next week. If you want to give it a try, here's the archive you can unzip and load in Chrome/Firefox according to [the instructions](https://github.com/zalmoxisus/redux-devtools-extension#1-for-chrome): [extension.zip](https://github.com/zalmoxisus/redux-devtools-extension/files/2683108/extension.zip)

A sneak peek:
![image](http://g.recordit.co/CwXmEO08K7.gif)

Apart from opening resource, as seen in the demo, it can open the file (and jump to the line-column) right in your editor. Pretty useful for debugging, and also as an alternative when there's not possible to use openResource (for Firefox or when using the extension from window or for remote debugging). When there's no openResource support, It'll suggest to specify your editor on Options Page, but you can click Settings button and enable that, also adding the path to your project root directory to append the paths to it. It works out of the box for VSCode, Atom, Webstorm/Phpstorm/IntelliJ, Sublime, Emacs, MacVim, Textmate on Mac and Windows. For Linux you can use [`atom-url-handler`](https://github.com/eclemens/atom-url-handler). 

By default the extension won't get stack traces, to not affect the performance, have to set `trace` option to `true` as in [examples](https://github.com/zalmoxisus/redux-devtools-extension/commit/64717bb9b3534ff616d9db56c2be680627c7b09d). I'll update the docs, but for more details see [instrumentation API](https://github.com/reduxjs/redux-devtools/tree/trace-stack/packages/redux-devtools-instrument#api).

For some edge cases where stack trace cannot be gotten with just `Error().stack`, you can pass a function to `trace` with your implementation (for example when [don't want to lose stack trace before calling `setTimeout`](https://github.com/reduxjs/redux-devtools/blob/trace-stack/packages/redux-devtools-instrument/test/instrument.spec.js#L842-L845)). It takes `action` object as argument and should return `stack` string. This way it can be also used to provide stack conditionally only for certain actions.

There's also an optional `traceLimit` parameter, which is `10` by default, to prevent consuming too much memory and serializing large stacks. It's useful for Firefox, as for Chrome call stack is limited to 10 anyway. However, even for Chrome it could be needed to get a larger stack than with 10 frames.

**Comment by zalmoxisus** [comment] 2018-12-19 14:58
Closing this. Refer to [`redux-devtools-trace-monitor`](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-trace-monitor) package for issues and pull requests. When `chrome.devtools.panels.openResource` will become available on Firefox it should work with the extension without any changes from our side. For now, opening in an external editor is a nice workaround. Thanks to everybody here for helping with this!

**Closed by zalmoxisus** 2018-12-19 14:58 UTC
