### ISSUE TITLE
No Actions when Store is composed with redux-replicate.

### ISSUE THREAD

**Issue by clubdesign** [zalmoxisus/redux-devtools-extension#93] opened 2016-04-17 17:52 UTC
Hey,

great work on this tool, but i am experiencing problems when the store is composed with redux-replicate before created, i don`t know where the root of the problem is, the only thin i know is: I deactivate the Replication, all actions are displayed correctly. I activate it the DevTools just get the init action and no more after that. The State shown by the init function is still updated though.

Even if is use the suggested implementation from redux-replicate:
```
import { createStore, combineReducers, compose } from 'redux';
import replicate from 'redux-replicate';
import localforage from 'redux-replicate-localforage';
import reducers from './reducers';

const initialState = {
  wow: 'such storage',
  very: 'cool'
};

const key = 'superCoolStorageUnit';
const replication = replicate(key, true, localforage);
const create = compose(replication)(createStore);
const store = create(combineReducers(reducers), initialState, DEVTOOLS HERE);
```

Can somebody confirm this?

**Comment by zalmoxisus** [comment] 2016-04-17 18:16
Hey @clubdesign,

Don't know if that is the reason, but you're mixing old redux api with the new one.

So if you use an old version of redux, it will be:
```js
const create = compose(replication, window.devToolsExtension)(createStore);
const store = create(combineReducers(reducers), initialState);
```

Or for the new one:
```js
const enhancer = compose(replication, window.devToolsExtension);
const store = createStore(combineReducers(reducers), initialState, enhancer);
```

**Comment by clubdesign** [comment] 2016-04-17 18:34
Hey @zalmoxisus ,

thanks for the suggest, but it still isn`t working, the above example is directly from redux-replicate, in my code i am doping it like this:

```
export default function configureStore( initialState ) {

  const replication = replicate(STORAGE_KEY, STORAGE_STATE_KEYS, localforage, initialState);
  const create = compose(replication, window.devToolsExtension)(createStore);
  const logger = createLogger(LOGGER_OPTIONS);

  const store_middleware = applyMiddleware( thunk, logger, routerMiddleware(browserHistory) );
  const store_enhancer = compose(store_middleware, replication, window.devToolsExtension() );

  const store = createStore(
    rootReducer,
    initialState,
    store_enhancer
  );

  return store
}
```

**Comment by zalmoxisus** [comment] 2016-04-17 18:37
That seems right. Don't you get any warnings/errors in the console? Does it work with vanilla Redux Devtools?

**Comment by clubdesign** [comment] 2016-04-17 18:39
Yes it works with Vanilla, and no Errors or anything elese, just the @INIT State. As said, the State keeps updating, but the dispatched action are not shown, see here: 

http://d.pr/i/1811t/15oqmzJQ

**Comment by zalmoxisus** [comment] 2016-04-17 18:44
I guess you mean redux logger middleware. By vanilla Redux DevTools I mean https://github.com/gaearon/redux-devtools. Please try to implement that instead of the extension, if that steal doesn't work, then more likely the problem is somewhere in `redux-replicate`. Usually, the described behaviour appears when the state is mutated.

**Comment by clubdesign** [comment] 2016-04-17 18:46
Nono, i mean the normal tools, i had them running correctly before i tried the extension. Everything is working.
Just as a hint: When i remove the replication, it is working normal and correctly, so maybe it`s something within redux-replicate what does not comly with the extension?

**Comment by zalmoxisus** [comment] 2016-04-17 18:47
That's interesting. I will try it.

**Comment by clubdesign** [comment] 2016-04-17 18:49
See: http://d.pr/i/13lXR/4PboxiX3

Is just replace everything back to Vanilla DevTools:

```
export default function configureStore( initialState ) {

  const replication = replicate(STORAGE_KEY, STORAGE_STATE_KEYS, localforage, initialState);

  const store_middleware = applyMiddleware( thunk, createLogger(LOGGER_OPTIONS), routerMiddleware(browserHistory) );
  const store_enhancer = compose(store_middleware, replication, DevTools.instrument() );

  const store = createStore(
    rootReducer,
    initialState,
    store_enhancer
  );

  return store
}
```

**Comment by zalmoxisus** [comment] 2016-04-17 19:04
Could you please try to add
```js
store.subscribe(() => { console.log(store.getState()); });
```
and check if you get the new value every time? If not then the problem should be investigated inside `redux-replicate`.

**Comment by clubdesign** [comment] 2016-04-17 19:06
Yes,  the state is logged with every action when subscribed.

**Comment by zalmoxisus** [comment] 2016-04-17 19:11
@clubdesign, thanks for confirming that. Then it is certainly a bug there, and that explains why we get only the first change, because the others are the same. When the subscription will work, the extension should work as well.

**Comment by zalmoxisus** [comment] 2016-04-17 19:12
@clubdesign, you are getting different values? because I got the same every time?

**Comment by clubdesign** [comment] 2016-04-17 19:14
Yes, the state in the console is updated correctly.

**Comment by zalmoxisus** [comment] 2016-04-17 19:29
Thanks for the details. Yes, due to the fact that [it replaces the reducer](https://github.com/loggur/redux-replicate/blob/master/src/index.js#L199) the extension don't get the new store. I'll investigate it.

**Comment by clubdesign** [comment] 2016-04-17 19:30
Ok, thanks @zalmoxisus !

**Comment by zalmoxisus** [comment] 2016-04-17 19:32
@clubdesign, actually not, I was wrong.
Using it like that
```js
const store_enhancer = compose(store_middleware, DevTools.instrument(), replication);
```
(change the order in the compose) should solve the issue. Please confirm.

I will add the information to the README.

**Comment by clubdesign** [comment] 2016-04-17 19:47
Sorry @zalmoxisus , i tried that already, but then the replication fails completly. But i can confirm, that the DevTools Work with this setup. But it doesn't help as the replcation is failing ;)

**Comment by zalmoxisus** [comment] 2016-04-18 09:57
Well, the problem is that `redux-replicate` creates the store twice (first time in [L180](https://github.com/loggur/redux-replicate/blob/master/src/index.js#L180) and the second one in [L133](https://github.com/loggur/redux-replicate/blob/master/src/index.js#L133)). Looks a a bit weird, but anyway fixed in https://github.com/zalmoxisus/redux-devtools-extension/commit/97eb9d320d3604bc97259e7c6845b24ba243b57b.

To get it work, you can install `v1.0.0.22` or wait few hours till chrome autoupdates the extension. If something is still wrong, feel free to reopen the issue.

**Closed by zalmoxisus** 2016-04-18 09:57 UTC

**Comment by clubdesign** [comment] 2016-04-18 10:14
Thx @zalmoxisus, will try it

**Comment by clubdesign** [comment] 2016-04-18 10:44
Can confirm it works with the current latest version @zalmoxisus.
Thanks!
