### ISSUE TITLE
After running my page, popped out windows don't update, toggling instance throws error

### ISSUE THREAD

**Issue by shadowii** [zalmoxisus/redux-devtools-extension#62] opened 2016-02-25 00:26 UTC
I tested the tool on the counter and todomvc pages, and it works. But after I start my site and try the extension on it, the extension stops working. Popped out windows don't seem to reflect changes to the state and when I try to change instances with the drop down, I get: 
```
Uncaught TypeError: Cannot read property 'remove' of undefined
i.rethrowCaughtError	@	window.bundle.js:1
v.processEventQueue	@	window.bundle.js:1
r	@	window.bundle.js:1
i.handleTopLevel	@	window.bundle.js:1
a	@	window.bundle.js:4
i	@	window.bundle.js:4
o.perform	@	window.bundle.js:2
f.batchedUpdates	@	window.bundle.js:3
i	@	window.bundle.js:2
m.dispatchEvent	@	window.bundle.js:4
```

Closing my page tab won't restore functionality to the plugin. I have to restart chrome. Not sure what's the cause. 

I will also occasionally get:
```
Uncaught TypeError: Cannot read property 'componentWillReceiveProps' of 
nullg.updateComponent @ window.bundle.js:2g.receiveComponent @ 
window.bundle.js:2i.receiveComponent @ window.bundle.js:2s.updateChildren @ 
window.bundle.js:4g.Mixin._reconcilerUpdateChildren @ window.bundle.js:4g.Mixin._updateChildren 
@ window.bundle.js:4g.Mixin.updateChildren @ window.bundle.js:4y.Mixin._updateDOMChildren @ 
window.bundle.js:3y.Mixin.updateComponent @ window.bundle.js:3y.Mixin.receiveComponent @ 
window.bundle.js:3i.receiveComponent @ window.bundle.js:2s.updateChildren @ 
window.bundle.js:4g.Mixin._reconcilerUpdateChildren @ window.bundle.js:4g.Mixin._updateChildren 
@ window.bundle.js:4g.Mixin.updateChildren @ window.bundle.js:4y.Mixin._updateDOMChildren @ 
window.bundle.js:3y.Mixin.updateComponent @ window.bundle.js:3y.Mixin.receiveComponent @ 
window.bundle.js:3i.receiveComponent @ window.bundle.js:2g._updateRenderedComponent @ 
window.bundle.js:2g._performComponentUpdate @ window.bundle.js:2g.updateComponent @ 
window.bundle.js:2g.receiveComponent @ window.bundle.js:2i.receiveComponent @ 
window.bundle.js:2g._updateRenderedComponent @ 
window.bundle.js:2g._performComponentUpdate @ window.bundle.js:2g.updateComponent @ 
window.bundle.js:2g.receiveComponent @ window.bundle.js:2i.receiveComponent @ 
window.bundle.js:2g._updateRenderedComponent @ 
window.bundle.js:2g._performComponentUpdate @ window.bundle.js:2g.updateComponent @ 
window.bundle.js:2g.receiveComponent @ window.bundle.js:2i.receiveComponent @ 
window.bundle.js:2s.updateChildren @ window.bundle.js:4g.Mixin._reconcilerUpdateChildren @ 
window.bundle.js:4g.Mixin._updateChildren @ window.bundle.js:4g.Mixin.updateChildren @ 
window.bundle.js:4y.Mixin._updateDOMChildren @ window.bundle.js:3y.Mixin.updateComponent @ 
window.bundle.js:3y.Mixin.receiveComponent @ window.bundle.js:3i.receiveComponent @ 
window.bundle.js:2g._updateRenderedComponent @ 
window.bundle.js:2g._performComponentUpdate @ window.bundle.js:2g.updateComponent @ 
window.bundle.js:2g.receiveComponent @ window.bundle.js:2i.receiveComponent @ 
window.bundle.js:2g._updateRenderedComponent @ 
window.bundle.js:2g._performComponentUpdate @ window.bundle.js:2g.updateComponent @
 window.bundle.js:2g.performUpdateIfNecessary @ window.bundle.js:2i.performUpdateIfNecessary 
@ window.bundle.js:2u @ window.bundle.js:2o.perform @ window.bundle.js:2o.perform @ 
window.bundle.js:2v.perform @ window.bundle.js:2E @ window.bundle.js:2o.closeAll @ 
window.bundle.js:2o.perform @ window.bundle.js:2f.batchedUpdates @ window.bundle.js:3i @ 
window.bundle.js:2m.dispatchEvent @ window.bundle.js:4
```

**Comment by zalmoxisus** [comment] 2016-02-25 09:27
Could you share an example to reproduce it or at least copy here your store configuration?

**Comment by shadowii** [comment] 2016-02-25 15:46
Definitely. I realize the uselessness of my logs, but that's all the error messaging I've got to work with, and my configuration didn't look particularly special:

```
const reduxRouterMiddleware = syncHistory(browserHistory);
[reduxRouterMiddleware, thunk];

const middleware = [reduxRouterMiddleware, thunk];
this.store = createStore(reducer, initialState, compose(
            applyMiddleware(...middleware),
            typeof window === "object" && typeof window.devToolsExtension !== "undefined" ? window.devToolsExtension() : f => f
            ));
```

I've eliminated hmr so it's not that. Though when I deleted initial state, the extension seemed to work. But I'm not sure why. I'll keep poking around there.

**Comment by zalmoxisus** [comment] 2016-02-25 17:00
It should be something in the `initialState` then which is causing the error. I would like to investigate this if you provide an example. To get more helpful errors (so you'll see what exactly throws and where), you should [run the extension in dev mode](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension).

**Comment by shadowii** [comment] 2016-02-25 18:45
I'll have to put this on the backburner for the moment, but I will definitely revisit. Thanks for the heads up on dev mode.

**Comment by zalmoxisus** [comment] 2016-04-04 11:19
Since https://github.com/zalmoxisus/redux-devtools-extension/pull/72 a lot of functionality was changed, so this should be fixed. Please give it try and we have time and if the issue persists, please reopen the issue with the details.

**Closed by zalmoxisus** 2016-04-04 11:19 UTC
