### ISSUE TITLE
Version : 2.8.2 CPU issue

### ISSUE THREAD

**Issue by Hamatek** [zalmoxisus/redux-devtools-extension#230] opened 2016-10-17 22:56 UTC
Hello, thanks for this great tool I have been using for months.

Unfortunately has of today new patch 2.8.2 I cannot use it anymore, as soon as open the dev tool extension, the CPU jump to 100% and freeze the web page I am working on.

Running on Ubuntu 14.04, Version 54.0.2840.59 (64-bit)

**Comment by zalmoxisus** [comment] 2016-10-18 07:16
@Hamatek, thanks for the report. Seems related to #226. There's nothing from the last changes which could cause that, but the process of updating could cause the issue.

If you open the extension's window and click on the instances select box, how many of them do you have there?

**Comment by Hamatek** [comment] 2016-10-18 13:26
@zalmoxisus  thanks for your quick respond, i think the extension updates itself every time one is available. when I check the instance select box I have only my localhost app in there.

**Comment by zalmoxisus** [comment] 2016-10-18 13:53
@Hamatek, when having that CPU issue don't you have multiple instances of your app added and removed as @okonet showed in #207?

![2016-09-06 at 22 51](https://cloud.githubusercontent.com/assets/11071/18290617/7d48da24-7484-11e6-8d2b-d1a480a3dda2.gif)

**Comment by zalmoxisus** [comment] 2016-10-18 13:54
According to Chrome docs, the extension shouldn't be updated till your app is inspected. So, it shouldn't cause any problems. Just in case I've addressed it in https://github.com/zalmoxisus/redux-devtools-extension/commit/f6bd08c8f0aef6882df38b6e5200c95fb1cc4a29. However, I suspect there's the problem above.

**Comment by Hamatek** [comment] 2016-10-18 14:13
@zalmoxisus I don't experience the same thing has shown above, in my case when opening the tool or reloading the page its stuck on  `No store found. Make sure to follow the instructions.` for like 5s to 10s, but once the tool loads only one instance is shown. 

below are more information about my setup:

``` javascript
// create the saga middleware
const sagaMiddleware = createSagaMiddleware();

const enhancers = compose(
    window.devToolsExtension ? window.devToolsExtension() : f => f
);
// const middleware = [thunk, createLogger(), sagaMiddleware];
const middleware = [sagaMiddleware];
const store = createStore(reducers, initialState, compose(
    applyMiddleware(...middleware),
    enhancers
));

// then run the saga
sagaMiddleware.run(rootSaga);
```

computer:
```
14GB RAM
i7 CPU 930 @ 2.80GHz × 8 
I use redux-sagas
```

CPU jump to 100% after first dispatch when redux devtool open, if devtool disabled CPU use is around 0

Thanks for your help @zalmoxisus

**Comment by zalmoxisus** [comment] 2016-10-18 14:26
So, the problem is only with the first dispatch, right? After those 5-10 seconds it works smoothly? Then it's just the matter of serializing lots of data.

Could you please try to disable the extension, install `npm i jsan` and add to the following:

```diff
+ import jsan from 'jsan';

// create the saga middleware
const sagaMiddleware = createSagaMiddleware();

const enhancers = compose(
    window.devToolsExtension ? window.devToolsExtension() : f => f
);
// const middleware = [thunk, createLogger(), sagaMiddleware];
const middleware = [sagaMiddleware];
const store = createStore(reducers, initialState, compose(
    applyMiddleware(...middleware),
    enhancers
));

+ setTimeout(() => { console.log(jsan.serialize(store.liftedStore.getState())) }, 1000);

// then run the saga
sagaMiddleware.run(rootSaga);
```

Just to confirm that after a second the application is stuck for some seconds during the state serialization.

**Comment by Hamatek** [comment] 2016-10-18 14:32
@zalmoxisus no its not its slow to load but when its up and action are dispatch it burns the CPU at 100%, I'll try what you suggest when Im at the office thanks.

**Comment by Hamatek** [comment] 2016-10-19 10:15
@zalmoxisus I tried the code above unfortunetly jsan.serialize throw an error so i switch it to jsan.stringify.
When I disable the redux dev tool and reboot the page I get instantaneously  `Uncaught TypeError: Cannot read property 'getState' of undefined(…)`

but if enable the plugin, the whole chrome devtool freeze and CPU lock 100% on the chrome dev tool tab (not on the app tab, and im not opening the redux dev tool)
Thus i don't get any logs... :(

**Comment by Hamatek** [comment] 2016-10-19 10:32
I tried with this  setup but its the same result
```javascript
import { composeWithDevTools } from 'redux-devtools-extension';

  const store = createStore(reducer, composeWithDevTools(
    applyMiddleware(...middleware),
    // other store enhancers if any
  ));
```

**Comment by zalmoxisus** [comment] 2016-10-19 10:57
@Hamatek, sorry, I should've been checked that. Yes, it's `jsan.stringify`, and yes you should enable the extension to have `store.liftedStore` object created.

As you can see, stringifying is causing the CPU spike as the object is very complex, and most likely you have circular references there (you can check it by replacing `jsan.stringify` with `JSON.stringify` and see it it will work). 

It doesn't see to be a regression of the latest version, unless you were disabling serialization in settings before.

**Comment by zalmoxisus** [comment] 2016-10-19 11:01
I'm working on an another approach to send data to the extension via shared workers without serializing it.

For now you can just set a lower value for `Limit the action history` on the Options page. 

Related to #159.

**Comment by Hamatek** [comment] 2016-10-19 12:37
@zalmoxisus thanks I tried JSON.strirngify as you mentioned but I do get `Uncaught TypeError: Converting circular structure to JSON` 

Also when i look at my redux state I don't have any circular references nor a very complex store, it was working just fine till yesterday i'm really confused now I must have done something wrong and somehow it was on the same date as the addon update ,sorry :(

Therefor I tried the addon on other website that enable redux devtools and I do not have any CPU issues.
Lastly I tried to remove  redux-saga from my middleware and it turn out that redux devtool is working just fine.

It seems something is going on with my sagas I will have to look into it... :(
Sorry for taking up your time and thanks for this fast support.

**Comment by Hamatek** [comment] 2016-10-19 12:54
I updated the redux-saga package and things are back to normal, not sure what was wrong.

**Comment by zalmoxisus** [comment] 2016-10-19 13:03
Thanks for the details. As I suspected, you had circular references, which take time to jsan to serialize. Glad you get rid of them. Then I'm closing it in favour of #159, which addresses the same issue, which I'll update when will have a solution for sending data without stringifying it.

If you have any other troubles feel free to file an issue.

**Closed by zalmoxisus** 2016-10-19 13:03 UTC
