### ISSUE TITLE
Redux DevTool tab stuck forever loading in Incognito mode

### ISSUE THREAD

**Issue by dstj** [zalmoxisus/redux-devtools-extension#597] opened 2018-11-28 22:26 UTC
Hi,

When using Chrome's incognito mode, the "Redux" tab in the Developer tools hangs displaying the preloader. but the "quick access extension button" works. This only happens in Incognito mode. See images

**Incognito mode**
![image](https://user-images.githubusercontent.com/467692/49186232-06097e80-f332-11e8-8391-70295ed0a879.png)

**Normal mode**
![image](https://user-images.githubusercontent.com/467692/49186344-5f71ad80-f332-11e8-8db3-48634312b259.png)

Chrome version: 70.0.3538.110 (Official Build) (64-bit)
Redux DevTool version: 2.16.3

The extension is properly enabled in incognito (_i.e._ it's not a duplicate of #521 ;) )

**Comment by zalmoxisus** [comment] 2018-11-28 22:49
Thanks for the details. I can reproduce it, getting "Background page failed to load" exception from chrome, so there's no access to extension's background script. I'll ship a patch tomorrow. Meanwhile you can us it from extension's windows instead of devpanel (right click on the page and select desired position from context menu).

**Comment by zalmoxisus** [comment] 2018-11-29 18:47
Fixed in `2.16.4`, which was published this morning on Chrome Store. Note that because we don't have access to the background store objects, it will be serialized again and could be slower and consuming more RAM depending on the state structure.

Feel free to reopen the issue if still experience problems with this.

**Closed by zalmoxisus** 2018-11-29 18:47 UTC
