### ISSUE TITLE
maxAge console spam

### ISSUE THREAD

**Issue by chrisblossom** [zalmoxisus/redux-devtools-extension#89] opened 2016-04-12 20:57 UTC
Is anyone else suddenly seeing this in their chrome console? Am I doing something wrong or is this expected?

```
maxAge 50 1
VM2605:1 maxAge 50 2
VM2605:1 maxAge 50 3
VM2605:1 maxAge 50 4
VM2605:1 maxAge 50 5
VM2605:1 maxAge 50 6
VM2605:1 maxAge 50 7
VM2605:1 maxAge 50 8
VM2605:1 maxAge 50 9
VM2605:1 maxAge 50 10
VM2605:1 maxAge 50 11
VM2605:1 maxAge 50 12
VM2605:1 maxAge 50 13
VM2605:1 maxAge 50 14
VM2605:1 maxAge 50 15
VM2605:1 maxAge 50 16
app.js:55 [HMR] connected
```

**Comment by MalcolmDwyer** [comment] 2016-04-12 21:11
Confirming... I started seeing it too as of an hour ago.
Version: 1.0.0.18
Updated: April 12, 2016

**Comment by arnerjohn** [comment] 2016-04-12 21:29
I'm just making a guess but it looks like the root of the problem may be due to a change here https://github.com/gaearon/redux-devtools/blob/master/src/createDevTools.js#L20-L23 from a recent PR that was merged into `redux-devtools`.

**Comment by andreigabreanu** [comment] 2016-04-12 22:49
Confirm I am seeing it also

**Comment by Calvein** [comment] 2016-04-13 02:17
Same problem here, in the meantime, I've just added this script to prevent them:

```js
console._log = console.log
console.log = function() {
  if (arguments[0] !== 'maxAge') {
    console._log.apply(console, arguments)
  }
}
```

**Comment by cjke** [comment] 2016-04-13 03:13
Another temporary options is switch on console Regex (if using Chrome) and add the following filter:
`^maxAge`

Mega quick and dirty until the problem is fixed

**Comment by cjke** [comment] 2016-04-13 03:16
Quick regex snippet for the Chrome console filter (with regex turned on):
^(?!maxAge).*$

Mega dirty, but temporary until root issue is fixed
![screenshot 2016-04-13 12 15 58](https://cloud.githubusercontent.com/assets/884065/14481813/84ac0b00-0171-11e6-99de-22f0f2cceb0b.png)

**Comment by zalmoxisus** [comment] 2016-04-13 07:55
Oh, sorry, just forgot to remove the console. Fill fix ASAP.

**Comment by born2net** [comment] 2016-04-13 16:16
+1 tx for fixing

**Closed** 2016-04-13 17:12 UTC
