### ISSUE TITLE
Reverse Order of Actions

### ISSUE THREAD

**Issue by tuckerconnelly** [zalmoxisus/redux-devtools-extension#38] opened 2016-01-20 11:49 UTC
When I open up the DevTools, I'm only really interested in the _current_ state, not the first one.

Would be nice if the actions were reversed, so the latest one was up top.

If I get some time, I'll do a PR, but this should be super quick to do if ya'll agree :)

(BTW, this tool is freakin' awesome!!)

**Comment by zalmoxisus** [comment] 2016-01-20 17:21
Thanks for the feedback and the suggestion!

I think solving the issue #34 would be enough, isn't it?

**Comment by tuckerconnelly** [comment] 2016-01-20 17:26
I think reverse order would be better--

Say you're up looking at an action from 10 actions ago, then boom, an action comes in and it autoscrolls you back down. Could get annoying :P 

Also having the latest action at the top matches most normal "feeds" around the web (facebook feed, twitter feed, etc. all have latest stuff at the top)

**Comment by zalmoxisus** [comment] 2016-01-21 08:07
> Say you're up looking at an action from 10 actions ago, then boom, an action comes in and it autoscrolls you back down. Could get annoying :P
Actually autoscrolling to the bottom works (the issue was only when you first open the window), and as you see it doesn't bother you when you scroll to a specific action (autoscrolling happens only when you are at the bottom).

I'm neither pro nor against this proposal, but it should be advocated and implemented on the [monitor side](https://github.com/gaearon/redux-devtools-log-monitor), otherwise we'll still have autoscrolling to bottom happen on the log monitor. It wouldn't be efficient and sustainable to revert actions' array and states' object every time an action is dispatched, way better to just [revert the loop](https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitor.js#L176). Also I want the extension behavior to be the same as Redux DevTools, so one could easy switch from the classical implementation of Redux DevTools to the extension and back.

**Comment by gaearon** [comment] 2016-01-29 16:44
The log monitor [should already autoscroll](https://github.com/gaearon/redux-devtools-log-monitor/blob/fbee23d4600bf864524ed5bc9c3e9e2ec0497794/src/LogMonitor.js#L107-L135) if you didn't scroll up manually.

**Comment by zalmoxisus** [comment] 2016-01-29 16:48
@gaearon, yes. The issue is about the initial rendering when having already a history tree in the liftedStore. We should have trigger that also for `componentDidMount`.

**Comment by gaearon** [comment] 2016-01-29 18:00
Ah right. I'm happy to accept a PR that scroll to bottom in `componentDidMount()` if the scrollTop received via props is `0`.

**Comment by zalmoxisus** [comment] 2016-01-30 14:01
@gaearon, I'm afraid it could be a problem for when using `persistState`. Let's say, I scrolled to the top, refreshed the page and the monitor autoscrolled to the bottom, which wouldn't be the expected result. So, we have to autoscroll on mounting only when `preserveScrollTop` is `false`. We don't need `preserveScrollTop` in the extension, but I have to figure out how to set monitors props depending on which are enabled.

**Comment by zalmoxisus** [comment] 2016-02-02 19:33
Should work in `v1.0.0-beta3`, but I'll keep the issue open till we have it merged in [`redux-devtools-log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor/pull/32).

Also the idea of reversed actions for the notifications is good and, actually, implemented in `Diff Monitor`. We could add this for the popup page to make the actions look as notifications (with what was changed) and to "match most of feeds around the web" if other users agree with it.

**Comment by zalmoxisus** [comment] 2016-05-15 18:04
In `v1.3.0` now it's possible now to select monitors directly in the monitor window, Chrome devtools panel or browser action popup. So it's up to you to add / use any custom monitors. Monitors are moved to `remotedev-app`, as it's just a simple web app, it's easier to add and test custom monitors. It's just [one file](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/containers/DevTools.js) to be changed.

**Closed by zalmoxisus** 2016-05-15 18:04 UTC
