### ISSUE TITLE
Cannot type the letter "p" in the dispatcher

### ISSUE THREAD

**Issue by Shard** [zalmoxisus/redux-devtools-extension#575] opened 2018-11-05 03:57 UTC
Steps to reproduce:

1. Open redux dev tools
2. Open inspector and the Redux tab
3. Open dispatcher panel
4. Type the letter p (lowercase, uppercase P works)

This occurred on Chromium for Mac, Version 71.0.3554.0 (Developer Build) (64-bit). Tested in incognito mode with only Redux Dev Tools extension enabled.

**Comment by qodesmith** [comment] 2018-11-13 10:54
This worked fine for me. Are you sure this isn't interference from another installed extension? For instance, one of the extensions I have installed has a listener for the `esc` key being pressed. Bother's the hell out of me when it spews errors in the console, but I know it's garbage. Perhaps something like that is going on.

**Comment by zalmoxisus** [comment] 2018-11-15 14:07
Checked in `72.0.3612.0 (Developer Build) (64-bit)` for Mac and cannot reproduce as well.
Steps:
1. Download latest Chromium build from https://download-chromium.appspot.com
2. Install extension from https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd
3. Open http://zalmoxisus.github.io/examples/counter/ and next following your steps.

Most likely @qodesmith is right, note that an extension can define a shortcut which will work outside the browser, so it will be suppressed even if you open incognito without other extensions. But on the other hand, if that's the case, you would have the issue with typing `p` also in browsers pages.

**Comment by Shard** [comment] 2018-11-19 05:42
I did some more testing and when I open up redux dev tools in chrome inspector, I can track down the the eventHandler that is eating the keypress event to a function called `forwardKeyboardEvent` inside a VM file which i believe is being defined by Redux Dev Tools.

At the end of the VM source, I find the following code (when formatted):
```
    )({
        "exposeExperimentalAPIs": false,
        "name": "Redux DevTools",
        "startPage": "chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/devtools.html"
    }, 332462400, "default", [3142, 704, 588, 2123, 2269, 2267, 1106, 2372, 2235, 2491, 2155, 2411, 2237, 2493, 2157, 2413, 2096, 2144, 2118, 114, 2119, 2375, 2384, 112, 447, 27, 2371, 2127, 2381, 2130, 2386, 2128], ()=>{}
    , injectedScriptId);
}
)("5d63b0d7-d555-42d3-b1da-c12b50275a54")
```

If I use chrome to remove the event handler (the only KeyPress handler found on the dispatcher field) then the `p` starts working for me.

**Comment by qodesmith** [comment] 2018-11-19 14:10
@Shard Have you tried temporarily disabling all other extensions and seeing if the behavior persists?

**Comment by zalmoxisus** [comment] 2018-11-19 18:30
@Shard can you reproduce it also from extension's window (not from dev panel)? To open it in a window, use the context menu from right on the web page or from extensions's icon.

**Comment by hscheuerle** [comment] 2020-10-26 20:03
Got the same thing with the 'h' key. Works when you find whatever extension is causing the issue. Don't forget to close all browser windows and all pwa apps after removing other extensions.

**Closed** 2024-11-10 13:16 UTC
Labels: cannot-reproduce
