### ISSUE TITLE
The devtool cannot work suddenly after devtool extension auto upgraded

### ISSUE THREAD

**Issue by DanielZhu** [zalmoxisus/redux-devtools-extension#283] opened 2017-01-12 03:16 UTC
Here's the screenshot

I haven't changed anything in my project, and then I found the redux-devtool-extension cannot work.

And I found that the extention auto upgraded itself in the background to 2.12.2

![image](https://cloud.githubusercontent.com/assets/1383798/21875578/0b439c8c-d8b8-11e6-8bca-6569c5579936.png)

Does anyone see this before? Thanks.

**Comment by zalmoxisus** [comment] 2017-01-12 09:36
Could you please provide more details about store configuration and data you use? If you could share a repro it would help a lot.

**Comment by DanielZhu** [comment] 2017-01-12 12:24
@zalmoxisus I found that it's working well without using Symbol.for('XXX_YYY') in actions, but it still wired as it broke suddenly.

**Comment by zalmoxisus** [comment] 2017-01-12 12:30
I guess the problem is related to the introduced support for Symbols in https://github.com/alexkuz/redux-devtools-inspector/pull/63. The idea is that `JSON.stringified` convert symbols to `undefined`. Could you please update the extension to `2.12.2.1` and see if it fixes the issue? You should get `<NULL>` now for your actions with symbols.

**Comment by zalmoxisus** [comment] 2017-01-14 09:47
Did you get a chance to check it on `2.12.2.1`?

**Comment by zalmoxisus** [comment] 2017-01-17 19:24
Closing since having Symbols doesn't break the Inspector anymore. However, if you want to get full support for `Symbol`, use `serialize` parameter as following:
```js
const store = Redux.createStore(reducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__({
 serialize: { 
   options: : true
   }
}
}));
```

**Closed by zalmoxisus** 2017-01-17 19:24 UTC
