### ISSUE TITLE
slider monitor not working

### ISSUE THREAD

**Issue by ginxwar** [zalmoxisus/redux-devtools-extension#109] opened 2016-05-10 04:34 UTC
I'm checking out the slider monitor with http://zalmoxisus.github.io/redux-devtools-extension/examples/counter/ but when I hit play, nothing happens.

Diff monitor and chart monitor all appear to be working, but the slider doesn't play back at all.

When I increment the counter a couple of times, I see that the slider monitor keeps track the number of the state changes.  But when playing back or manually sliding the slide bar, the actual state of the Counter app does not change.

I'm using v1.2.0 of the Chrome plugin

**Comment by bjbrewster** [comment] 2016-05-10 04:47
I also have v1.2.0 of the Chrome Extension and the Slider Monitor no longer works. :(

**Comment by zalmoxisus** [comment] 2016-05-10 09:02
I cannot reproduce it. Could you check if there are more instances, there's select box in the Slider window, and eventually try to select an instance explicitly?

**Comment by ginxwar** [comment] 2016-05-10 16:03
I have a single instance of the counter app example.  It's set to that instance and not to "autoselect instances"

I have tried this on both Chrome latest and Canary latest.  Slider monitor still doesn't work right.

I've also noticed that the "skip" button in the inspector monitor doesn't really do anything either.  I would guess that the skip button would change my state.  So it seems the only monitor that truly affects the state is the main monitor right when you click on the Redux tab (aka the main monitor where you see Reset, Revert, Sweep, Commit) .  When clicking on those actions in the main monitor, I can see that it directly affects the state.

However, all other monitors appear to be only reading the state.

**Comment by zalmoxisus** [comment] 2016-05-13 15:26
@ginxwar, @bjbrewster, I've published yesterday a new version, it should be updated automatically. Please check if the problem still persists.

**Comment by ginxwar** [comment] 2016-05-14 03:25
Hm, sorry, but the issue still remain.  Anything I could do to help dump logs and give you more information as to why this is occurring?

**Comment by canaandavis** [comment] 2016-05-14 07:28
I am also seeing an issue with the slide and diff monitor, using version 1.2.1

Seems like the chart monitor and inspector monitor are working ok though.

Chrome 50.0.2661.102
OSX 10.10.5

**Comment by zalmoxisus** [comment] 2016-05-14 07:59
Is the same problem with [our examples](https://github.com/zalmoxisus/redux-devtools-extension#examples)? Could you try to remove the extension (from `chrome://extensions/`) and [install](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) again?

**Comment by canaandavis** [comment] 2016-05-14 16:30
Well in my case, the age old "have you tried restarting it?" has seemed to have resolved the issue.  

I uninstalled the plugin reinstalled it, and now the example apps, and my project are working again.

@zalmoxisus Thank you for your fast response, and all of your work on this project.  It is much appreciated!

**Comment by ginxwar** [comment] 2016-05-15 02:09
@zalmoxisus I also tried uninstalling and reinstalling.  Still no go.  The slider monitor shows the number of state changes but moving the slider manually or hitting play or clicking on the back/forward buttons do not make changes to the state.  I'm on 1.2.1.

Chrome Canary: 52.0.2735.0 (64-bit)
OSX: 10.11.4

**Comment by zalmoxisus** [comment] 2016-05-15 08:08
@canaandavis, @ginxwar, thanks for the details! Yes, after you open it form Chrome devtools panel, it commands from windows don't work anymore. I've fixed it in https://github.com/zalmoxisus/redux-devtools-extension/commit/8a2f47e647db2688756eae80701c40309ad1de07. Still have to finish some work in progress and will publish to Chrome store.

**Comment by zalmoxisus** [comment] 2016-05-15 17:52
Fixed in `v1.3.0`. Also now it'd possible to switch monitors and toggle the slider monitor directly in the Chrome devtools panel. Feel free to reopen the issue, if there are any troubles.

**Closed by zalmoxisus** 2016-05-15 17:52 UTC
Labels: bug

**Comment by ginxwar** [comment] 2016-05-15 20:20
it's working now!  Thanks @zalmoxisus

**Comment by bjbrewster** [comment] 2016-05-16 01:23
This is fixed for me as well.  I like able to toggle the slider in the main docked dev tool window too.

Thank you very much :)

**Comment by canaandavis** [comment] 2016-05-16 04:20
@zalmoxisus Just had a chance to check out the updates, and everything is working great!

Also, I really like the changes to the interface, much easier to use, thank you!

**Comment by PhilippeRoy** [comment] 2017-09-14 10:00
@zalmoxisus First off, great tool!

Second. I'd like to re-open this issue as I am having similar issues ATM. This may be related to [#375](https://github.com/zalmoxisus/redux-devtools-extension/issues/375)

The issue I have is in relation to Dan Abramov response to dynamically loading reducers http://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application. All the monitors work when I dynamically load a reducer except for the Slide monitor. I tried `store.liftedStore.getState()` and all the values seem correct. But when I try to replay actions with the Slide monitor nothing happens. 

Let me know if you need me to provide any more details. 

Cheers
